### ISSUE TITLE
Value cannot ben null or empty string. Parameter name: value

### ISSUE THREAD

**Issue by DenZuck** [NModbus/NModbus#35]
I've downloaded the project and when compile in "Release" I get the error:

Description: Value cannot ben null or empty string. Parameter name: value
Project: NModbus.Serial
File: NuGet.Build.Tasks.Pack.targets

I don't get the error complilng in "Debug" mode. Any idea how to solve ?

**Comment by rquackenbush** [comment]
@DenZuck - apologies for the incredibly late reply. This is due to how I set up the nuspec file for the NModbus.Serial project. I made the (invalid) assumption that the only thing that would run the Release build is the build server. The build server is configured to specify the value for `$version$`.

```xml
<dependencies>
        <group >
             <dependency id="NModbus" version="$version$" />
        </group>
```
