### ISSUE TITLE
Aborted connection.

### ISSUE THREAD

**Issue by LucVerstreken** [NModbus/NModbus#48]
I try to read input registers from a Cobot, via TCP-IP NModBus but I get each time the following exception:

"Unable to read data from the transport connection: An established connection was aborted by the software in your host machine."

Does this mean that the cobot has made a disconnect?

**Comment by Fuchks** [comment]
I would recommend to log the traffic with wireshark, this gives you deep insight what's going on.
It could be an abort due to timeout, but without deeper inspection this is just one possibility from many.

I'd like to refer to Stackoverflow: https://stackoverflow.com/questions/14304658/c-sharp-an-established-connection-was-aborted-by-the-software-in-your-host-machi
