### ISSUE TITLE
SlaveStorage() not found

### ISSUE THREAD

**Issue by leocplr** [NModbus/NModbus#59]
Hello!
I'm trying to run the examples to create a Serial RTU Slave with custom message or other data, but my code can't find The SlaveStorage().
I found the SlaveDataStore() on GIT that could solve my problem, but at my v3.0.60 version intalled from nuget, this file is different. It's without InputRegister, HoldingRegister, etc, declaration.

Here is part of example. (StartModbusSerialRtuSlaveWithCustomMessage)

                var acTechDataStore = new SlaveStorage();

                acTechDataStore.InputRegisters.StorageOperationOccurred += (sender, args) => Console.WriteLine($"ACTECH Input registers: {args.Operation} starting at {args.StartingAddress}");
                acTechDataStore.HoldingRegisters.StorageOperationOccurred += (sender, args) => Console.WriteLine($"ACTECH Holding registers: {args.Operation} starting at {args.StartingAddress}");

                var danfossStore = new SlaveDataStore();// SlaveStorage();

                danfossStore.InputRegisters.StorageOperationOccurred += (sender, args) => Console.WriteLine($"DANFOSS Input registers: {args.Operation} starting at {args.StartingAddress}");
                danfossStore.HoldingRegisters.StorageOperationOccurred += (sender, args) => Console.WriteLine($"DANFOSS Holding registers: {args.Operation} starting at {args.StartingAddress}");

Thanks!

**Comment by rquackenbush** [comment]
Hi @leocplr - the class `SlaveStorage` is part of the [Samples project](https://github.com/NModbus/NModbus/blob/develop/Samples/SparsePointStorage.cs#L8). It is there as an example of how to implement the `ISlaveDataStore` interface. It is not part of the Nuget package.

I think I see what you're running into with the `SlaveDataStore` class. It implements the `ISlaveDataStore` interface explicitly. One way to get at the implementation of the registers is to use a variable of type `ISlaveDataStore`:

```c#
ISlaveDataStore dataStore = new SlaveDataStore();
```

instead of:

```c#
var dataStore = new SlaveDataStore();
```

I can see where this isn't intuitive at all. In the next release of NModbus, I'll make `SlaveDataStore` implement `ISlaveDataStore` using public members.
